node {
    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    
    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk melanjutkan ekseskusi pipeline ke tahap deploy atau "Abort" untuk menghentikan eksekusi pipeline)'

        }
        
        // Always publish test results
        post {
            always {
                junit 'test-reports/results.xml'
            }
        }
    }
    
    stage('Deliver') {
        docker.image('cdrx/pyinstaller-linux:python2').inside {
            sh 'pyinstaller --onefile sources/add2vals.py'
            sleep 60
        }
        
        // Archive artifact on success
        post {
            success {
                archiveArtifacts 'dist/add2vals'
            }
        }
    }
}
